### ISSUE TITLE
only most left IPv4 last octet is zero out

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa-ip-anonymity#4]
**Describe the bug**
1, It works only there is one XFF, if there are more than one set of XFF, typical in multiple level http proxy world, only most left  IPv4 last octet is zero out
2, true client IP gets exposed in ```Forwarded: for=xxx.xxx.xxx.xxx```
3, true client IP gets exposed in ```X-Real-Ip```

**To Reproduce**
http://spm.pathfinder.gov.bc.ca/httpbin/get?show_env=1 

**Expected behavior**
1, all IPv4 in XFF header gets zero out last octet
2, true client IP should not be exposed, expected also last octet zero for all IPs in  header ```Forwarded: for=xxx.xxx.xxx.xxx``` and ```X-Real-Ip``` 

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS High Sierra]
 - Browser [chrome, safari]
 - Version [chrome:v67, safari:v11.1]

**Additional context**
same XFF behaviour in ```origin:```

**Comment by pauldaustin** [comment]
Leo,

Use this to dump the raw headers 
http://bcgov.revolsys.com/dump.php

**Comment by ll911** [comment]
http://spm.pathfinder.gov.bc.ca/dump.php

**Comment by pauldaustin** [comment]
Leo,

I think you forgot to enable the gwa-ip-anonymity plugin for that new API.

If I wanted to try a few things out in terms of plugins (the request transformer). Is there a URL that get’s mapped to API’s created using the delivery kong.

Can you create an API in delivery using my dump.php and send me the URL that I can access it via.

Thanks,
Paul

**Comment by ll911** [comment]
check again.  oops, i forgot turn on the plugin

**Comment by pauldaustin** [comment]
Can you try 1.0.3-0?

I have added the forwarded header to the list of headers that I replace values in.

As far as I can tell it is not possible to change the X-Real-IP value as it is set before kong plugins are called and is then readonly.

**Comment by ll911** [comment]
i see only only two sets of IPv4 in XFF now. 
X-Real-IP and Forwarded header still the same, I understand if they are readonly, but we can not have them not passed to upstream right? 
X-Real-IP is defined by nginx module
http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_header

**Comment by pauldaustin** [comment]
Forwarded should have been updated.

I need to know where this gets set originally in the chain of requests.

I had to fake the Forwarded header in my apache that calls my kong.

In a kong plugin I can’t do anything about X-Real-IP. You might be able in the kong config to completely disable that Nginx module.

**Comment by ll911** [comment]
gateway still need x-real-ip, just need to mask for upstream services. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded 
Forwarded header is a combination of XFF, XFH and XFP

**Comment by ll911** [comment]
I found out Forwarded header can be muted by request transformer plugin

**Comment by pauldaustin** [comment]
Leo,

Looks like I needed to create a pull request before I tagged the release.

That’ll fix the Forwarded header.

Try 1.0.4-0.

I can’t do anything about the X-Real-IP

**Comment by pauldaustin** [comment]
You might be able to get it to work if the Nginx config has

proxy_set_header X-Real-IP "";

Can you try 1.0.5-0?

It fixes the removal of one of the X-Forwarded-For fields.

Did you add a kong plugin to delete the Forwarded header? If so can you disable that to see if the header is 0’d out

**Comment by ll911** [comment]
x-real-ip cannot be removed as it's part of the core that's required by gateway itself.
i cannot change nginx conf as they are managed by kong, however, i can change the header for x-real-ip to extract the value from, now i have it set to extract the value from self, it will get the pod IP, not clientIP, not ideal, but better than exposing clientIP to upstream.

**Comment by ll911** [comment]
clientIP no longer exposed to upstream, 
x-real-ip exposed with ```self```.
